Lab 2 Controlling a Motor_Driver w/ a Task: task_user Class Reference
task_user Class Reference
This task will interact with the user and make the motors operate based on their input.
#include <task_user.h>
Public Member Functions
task_user (const char *, unsigned portBASE_TYPE, size_t, emstream *)
This constructor creates a user interface task object.
void run (void)
This method runs when the 'task_user' is called.
Protected Member Functions
void print_help_message (void)
This method displays a simple help message telling the user what to do.
void show_status (void)
This method displays information about the status of the system.
bool hasUserInput (void)
Method returns true if the user has typed somthing into the terminal window.
void getNumberInput (void)
Method extracts the number entered by the user and places it into private variable 'number_entered'.
void printMotorMenu (void)
Prints the opening menu when the user enters the 'Main Motor Module' in case1.
void printMainMenu (void)
Prints the Main Menu at the beginning of the program.
void printSingleMotorOptions (void)
Prints the Single Motor Menu after the user has entered from the 'Main Motor Module'.
void printDashBoard (void)
Prints useful information about each motor like directive, power, and direction.
void setMotor (uint8_t, int16_t, uint8_t)
Method that takes the motor number, motor power, and directive and sets the correct motor to that directive at the apporpriate power level.
void resetMenus (void)
This Method resets the 'run once' lock on each print menu method so that it can be run again.
bool isValidMotor (int16_t)
Method checks whether the motor number entered is valid and within range (<2) right now.
Protected Attributes
bool is_menu_visible
Holds true if there is a menu currently printed on the screen, false otherwise.
Detailed Description
This task will interact with the user and make the motors operate based on their input.
Definition at line 79 of file task_user.h.
Constructor & Destructor Documentation
task_user::task_user (const char * a_name, unsigned portBASE_TYPE a_priority, size_t a_stack_size, emstream * p_ser_dev)
This constructor creates a user interface task object.
Constructor that creates a new task to interact with the user. All incoming paramters are initialized in the parent class construtor TaskBase.
Added new initializations for private variables added in order to clean up the clutter in the main case statement in the 'run()' method.
Parameters
[in] a_name A character string which will be the name of this task
[in] a_priority The priority at which this task will initially run (default: 0)
[in] a_stack_size The size of this task's stack in bytes (default: configMINIMAL_STACK_SIZE)
p_ser_dev Pointer to a serial device (port, radio, SD card, etc.
Definition at line 90 of file task_user.cpp.
References FREEWHEEL, and is_menu_visible.
Member Function Documentation
void task_user::getNumberInput (void) protected
Method extracts the number entered by the user and places it into private variable 'number_entered'.
Method gets the number being entered by the user.
This method uses a loop to constantly look for input until a return or escape symbol occurs. It then places the extracted negative or positive value in local class varible 'number_entered'.
Definition at line 668 of file task_user.cpp.
References p_print_ser_queue.
Referenced by run().
bool task_user::hasUserInput (void) protected
Method returns true if the user has typed somthing into the terminal window.
Method checks if the user has made an input.
Returns
returns TRUE if the user has made an input and places that charater into the class variable 'char_in'. Returns FALSE otherwise.
Definition at line 650 of file task_user.cpp.
Referenced by run().
bool task_user::isValidMotor (int16_t motor_number) protected
Method checks whether the motor number entered is valid and within range (<2) right now.
Method checks if the motor selected is a valid input.
Parameters
[in] motor_number The number number entered by the user.
Returns
returns TRUE if the motor value is valid, FALSE otherwise
Definition at line 803 of file task_user.cpp.
Referenced by run().
void task_user::print_help_message (void) protected
This method displays a simple help message telling the user what to do.
This method contains the old main menu that has extra information and avaliable options.
Definition at line 632 of file task_user.cpp.
References PROGRAM_VERSION.
Referenced by run().
void task_user::printDashBoard (void) protected
Prints useful information about each motor like directive, power, and direction.
Method prints out useful information about both motors.
Only print the menu if the is_menu_visible flag is false. This is so that it doesn't inifinitely print as the user is trying to input a value or trying to read it. Furthermore, it prints out 'status', 'power', & 'direction'
Definition at line 523 of file task_user.cpp.
References BRAKE, FREEWHEEL, is_menu_visible, POTENTIOMETER, and SETPOWER.
Referenced by run().
void task_user::printMainMenu (void) protected
Prints the Main Menu at the beginning of the program.
Method prints out the main menu, which is the first thing the user sees.
Menu is designed so that Control and testing modules are one part and all other operations like the ones included in the given version of this class are sectioned off accordingly.
Definition at line 453 of file task_user.cpp.
References is_menu_visible, and PROGRAM_VERSION.
Referenced by run().
void task_user::printMotorMenu (void) protected
Prints the opening menu when the user enters the 'Main Motor Module' in case1.
Method prints out the 'Main Motor Module' menu.
Only print the menu if the is_menu_visible flag is false. This is so that it doesn't inifinitely print as the user is trying to input a value or trying to read it.
Definition at line 478 of file task_user.cpp.
References is_menu_visible.
Referenced by run().
void task_user::printSingleMotorOptions (void) protected
Prints the Single Motor Menu after the user has entered from the 'Main Motor Module'.
Method prints out the 'Single Motor Control Module' menu.
Only print the menu if the is_menu_visible flag is false. This is so that it doesn't inifinitely print as the user is trying to input a value or trying to read it.
Definition at line 501 of file task_user.cpp.
References is_menu_visible.
Referenced by run().
void task_user::resetMenus (void) protected
This Method resets the 'run once' lock on each print menu method so that it can be run again.
Method resets the is_menu_visible flag so that another menu may be printed.
Definition at line 816 of file task_user.cpp.
References is_menu_visible.
Referenced by run().
void task_user::run (void)
This method runs when the 'task_user' is called.
This method is called by the RTOS once to run the task loop for ever and ever.
This method runs inifitely when the task is called so all logic is contained in here. A for(;;) loop runs until it gets to the end where it delays for 1 ms to allow other lower level priority tasks a chance to run.
Definition at line 122 of file task_user.cpp.
References BRAKE, FREEWHEEL, getNumberInput(), hasUserInput(), isValidMotor(), motor_power, motor_select, POTENTIOMETER, print_help_message(), printDashBoard(), printMainMenu(), printMotorMenu(), printSingleMotorOptions(), resetMenus(), setMotor(), SETPOWER, and show_status().
void task_user::setMotor (uint8_t motor_id, int16_t power, uint8_t direct) protected
Method that takes the motor number, motor power, and directive and sets the correct motor to that directive at the apporpriate power level.
Method sets motor to the correct state as specified by user.
This method sets the global registers to the correct values so that 'task_motor' can affect the correct motor. Also sets appropriate local values to store the state of this motor so that when 'printDashBoard()' is called it can print info on each motor because the global registers can only hold info for one motor at a time.
Parameters
[in] motor_id The motor select identifier
[in] power The power setting specified by the user in the run()
[in] direct The directive, or what we want the motor to do
Definition at line 776 of file task_user.cpp.
References motor_directive, motor_power, and motor_select.
Referenced by run().
void task_user::show_status (void) protected
This method displays information about the status of the system.
This method displays information about the status of the system, including the following:
The name and version of the program
The name, status, priority, and free stack space of each task
Processor cycles used by each task
Amount of heap space free and setting of RTOS tick timer
Definition at line 739 of file task_user.cpp.
References PROGRAM_VERSION.
Referenced by run().
The documentation for this class was generated from the following files:
task_user.h
task_user.cpp